events {}

http {

    upstream backend {

        server project07_web:8080;

    }

    server {

        listen 8080;

        location / {

            proxy_pass http://backend;

        }

    }

}
