# Docker Lab 01 – Hello Container

# Project Overview

This lab introduces the most important Docker commands used daily by DevOps Engineers, Cloud Engineers, SREs, Platform Engineers, and Application Support teams.

The objective was to deploy an Nginx container, inspect it, troubleshoot it, analyze running processes, view logs, access the container shell, and finally stop and remove the container.

This lab focuses on the core Docker lifecycle:

Create → Run → Monitor → Troubleshoot → Stop → Remove

---

# Architecture

Host (WSL Ubuntu)
│
├── Docker Engine
│
└── Nginx Container
│
├── Port 80 (Container)
│
└── Port 8080 (Host)

Browser
│
└── http://localhost:8080

---

# Lab Objectives

- Run first Docker container
- Learn detached mode
- Learn port mapping
- View running containers
- Stream container logs
- Access container shell
- Investigate container operating system
- Install troubleshooting tools
- View running processes
- Stop containers
- Remove containers

---

# Step 1 – Run Container

```bash
docker run -d -p 8080:80 --name webserver nginx
```

## Command Breakdown

docker run
- Creates and starts a container

-d
- Detached mode
- Container runs in background

-p 8080:80
- Host Port = 8080
- Container Port = 80

--name webserver
- Assigns friendly container name

nginx
- Docker image

---

# Understanding Port Mapping

```bash
-p HOST_PORT:CONTAINER_PORT
```

Example:

```bash
-p 8080:80
```

Meaning:

Browser
↓

localhost:8080

↓

Docker

↓

Container Port 80

---

# Step 2 – Verify Running Container

```bash
docker ps
```

Purpose:

Shows running containers.

Important columns:

- CONTAINER ID
- IMAGE
- COMMAND
- CREATED
- STATUS
- PORTS
- NAMES

---

# Step 3 – View Logs

```bash
docker logs -f webserver
```

## Flag Breakdown

logs
- Displays container logs

-f
- Follow logs continuously

Equivalent to:

```bash
tail -f logfile
```

Exit:

```bash
CTRL+C
```

---

# What Are Container Logs?

Container logs are stdout/stderr generated by the application.

For Nginx they include:

- Startup messages
- Errors
- Access requests
- Configuration information

---

# Step 4 – Enter Container

```bash
docker exec -it webserver bash
```

## Flag Breakdown

exec
- Execute command inside container

-i
- Interactive mode

-t
- Terminal mode

bash
- Launch shell

---

# Why Use docker exec?

Used constantly in production environments for:

- Troubleshooting
- Configuration checks
- Log review
- Network testing
- Package installation

---

# Step 5 – Explore Filesystem

```bash
ls
```

Observed directories:

```text
bin
etc
usr
var
tmp
root
proc
sys
```

This demonstrates that a container contains a complete Linux filesystem.

---

# Step 6 – Identify Operating System

```bash
cat /etc/os-release
```

Output:

```text
Debian GNU/Linux 13 (trixie)
```

Important lesson:

Container images are usually based on Linux distributions such as:

- Debian
- Ubuntu
- Alpine
- Rocky Linux

---

# Step 7 – Why ps Failed

Attempt:

```bash
ps aux
```

Result:

```text
ps: command not found
```

Reason:

Containers are intentionally minimal.

To reduce image size, many packages are removed.

Common missing tools:

- ps
- top
- ping
- curl
- nano
- netstat

---

# Step 8 – Install procps

```bash
apt update
apt install -y procps
```

## What Is procps?

Package containing:

```bash
ps
top
free
uptime
pkill
pgrep
```

Why installed:

Needed to inspect running processes.

---

# Step 9 – Analyze Processes

```bash
ps aux
```

Observed:

```text
nginx master process
nginx worker process
bash
```

Most important process:

```text
PID 1
```

Output:

```text
nginx: master process nginx -g daemon off;
```

---

# Why PID 1 Matters

Docker monitors PID 1.

If PID 1 exits:

Container exits.

This is one of the most important Docker concepts.

---

# Understanding

```bash
nginx -g 'daemon off;'
```

## What is -g ?

-g means:

Global configuration directive.

Example:

```bash
nginx -g 'daemon off;'
```

Tells Nginx:

Apply directive globally.

---

# Why daemon off?

Traditional Linux:

```bash
nginx
```

Nginx backgrounds itself.

Docker does NOT want applications to run in background.

Docker wants:

```text
One foreground process
```

Therefore:

```bash
nginx -g 'daemon off;'
```

keeps Nginx running in foreground.

Without this:

Container exits immediately.

---

# Step 10 – Stop Container

```bash
docker stop webserver
```

Purpose:

Gracefully stop container.

Verification:

```bash
docker ps -a
```

Status becomes:

```text
Exited (0)
```

---

# Exit Code Meaning

0
- Successful shutdown

1
- Generic error

127
- Command not found

255
- Fatal application failure

---

# Step 11 – Remove Container

```bash
docker rm webserver
```

Purpose:

Delete stopped container.

Verify:

```bash
docker ps -a
```

Container no longer exists.

---

# Docker Lifecycle

Create Container

```bash
docker run
```

View Running Containers

```bash
docker ps
```

View Logs

```bash
docker logs
```

Access Container

```bash
docker exec
```

Stop Container

```bash
docker stop
```

Delete Container

```bash
docker rm
```

---

# Real World Usage

These commands are used daily for:

- Application troubleshooting
- Production support
- Incident response
- Kubernetes node troubleshooting
- CI/CD validation
- Container health checks

---

# Interview Questions

Q: Difference between docker ps and docker ps -a?

A:
docker ps shows running containers.
docker ps -a shows all containers.

---

Q: Why did ps not exist inside container?

A:
Minimal image design removes unnecessary packages.

---

Q: Why does Docker care about PID 1?

A:
Container lifecycle is tied to PID 1.

---

Q: Why use daemon off?

A:
Keeps main process in foreground so container remains alive.

---

# Skills Learned

- Docker run
- Docker ps
- Docker logs
- Docker exec
- Docker stop
- Docker rm
- Port mapping
- Linux process inspection
- Package installation
- Container troubleshooting
- Nginx process analysis
- PID 1 concept

---

# Lab Summary

Successfully deployed, investigated, monitored, and removed an Nginx container while learning the most commonly used Docker commands used in real-world DevOps and Cloud Engineering environments.

This lab forms the foundation for all future Docker, Kubernetes, ECS, EKS, and containerized application deployments.
